config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
    resources :projects
  end

  default_url_options :host => "http://localhost:3000"

  root 'static#home'

  resources :chapters

  get "wait" => "wait#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<footer id="footer" class="footer footer-wrapper">
  <div class="row">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="wrapper">
            <ul>
              <li><a href="https://www.facebook.com/groups/CircleofYoungIntrapreneurs/" target="_blank"><i class="fa fa-facebook fa-2x"></i></a></li>
              <li><a href="https://twitter.com/circleofyi?lang=en" target="_blank"><i class="fa fa-twitter fa-2x"></i></a></li>
              <li><a href="https://www.instagram.com/thecircleofyi/?hl=en" target="_blank"><i class="fa fa-instagram fa-2x"></i></a></li>
              <li><a href="https://www.youtube.com/channel/UCtM8zWux6MF5CGAXcNqLuwg/videos" target="_blank"><i class="fa fa-youtube fa-2x"></i></a></li>
              <li><a href="https://www.linkedin.com/company/circle-of-young-intrapreneurs" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a></li>
            </ul>
          </div>
          <div class="copy-text">Copyright © Circle of Young Intrapreneurs 2015-2018</div>
        </div>
      </div>
    </div>
  </footer>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag '/images/logo_200.png', class: "img-responsive", id: 'coyi-logo', alt: 'Site Logo'%>
      </a>

        <ul class="collapse nav navbar-collapse navbar-nav">
          <li><a href="https://www.facebook.com/groups/CircleofYoungIntrapreneurs/" target="_blank"><i class="fa fa-facebook fa-2x"></i></a></li>
          <li><a href="https://twitter.com/circleofyi?lang=en" target="_blank"><i class="fa fa-twitter fa-2x"></i></a></li>
          <li><a href="https://www.instagram.com/thecircleofyi/?hl=en" target="_blank"><i class="fa fa-instagram fa-2x"></i></a></li>
          <li><a href="https://www.youtube.com/channel/UCtM8zWux6MF5CGAXcNqLuwg/videos" target="_blank"><i class="fa fa-youtube fa-2x"></i></a></li>
          <li><a href="https://www.linkedin.com/company/circle-of-young-intrapreneurs" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a></li>
        </ul>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li class="nav-link"><%= link_to 'Project Hub', user_projects_path(current_user) %></li>
        <li class="nav-link"><%= link_to 'Resources', resources_path(current_user) %></li>
        <%end%>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%if user_signed_in? %>
            <li><span class="navbar-text">Logged in as <strong><%=current_user.first_name %></strong></span>
            </li>

            <li>
              <%= link_to "My Profile", user_path(current_user), class:'nav-link' %>
            </li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'nav-link' %></li>
        <%else%>
            <li><%= link_to 'Sign up', new_user_registration_path, class:'nav-link' %></li>
            <li><%= link_to 'Login', new_user_session_path, class:'nav-link' %></li>
        <%end%>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>