config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
    resources :projects
  end

  default_url_options :host => "http://localhost:3000"

  root 'static#home'

  resources :chapters

  get "wait" => "wait#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  validate :word_count_is_more_than_250

  private

  def word_count_is_more_than_250
    errors[:intro] << "Maximum 250 words" if intro.split.size > 250
    errors[:impact] << "Maximum 250 words" if impact.split.size > 250
    errors[:businesscase] << "Maximum 250 words" if businesscase.split.size > 250
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @user = User.find(params[:user_id])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @user = User.find(params[:user_id])
  end

  # GET /projects/new
  def new
    @project = Project.new
    @user = User.find(params[:user_id])
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @user = User.find(params[:user_id])

    respond_to do |format|
      if @project.save
        UserMailer.project_pitch(@user,@project).deliver_now
        format.html { redirect_to user_projects_url(@user), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @user = User.find(params[:user_id])

    @project.destroy
    respond_to do |format|
      format.html { redirect_to user_projects_path(@user), notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :intro, :impact, :businesscase, :user_id)
    end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, url:[@user, @project], local: true) do |form| %>
  <% if project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

    <ul>
      <% project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <div class="form-group">
        <%= form.label :title, "Product Intro" %> <br>
        <%= form.text_field :title, placeholder: "Enter your project title", class: "form-control projectText", rows:"3"%>
        <small>What is the name of your project?</small>
      </div>

    <div class="form-group">
      <%= form.label :intro, "Project Introduction" %> <br>
      <%= form.text_area :intro, placeholder: "Enter your project introduction here", class: "form-control projectText", rows:"3"%>
      <small>Give an overview of your project here (300 words) </small>
    </div>

    <div class="form-group">
      <%= form.label :impact, "Social Impact" %> <br>
      <%= form.text_area :impact, class: "form-control projectText",rows:"3", placeholder: "Enter your social impact(s) here"%>
      <small>Outline the social impacts from your project and the positive impacts it can bring (300 words)</small>
    </div>

    <div class="form-group">
      <%= form.label :businesscase, "Business Case" %> <br>
      <%= form.text_area :businesscase, class: "form-control projectText", rows:"3", placeholder: "Enter your business case here"%>
      <small>What is the commercial return? What are the benefits to the sponsoring company? (300 words)</small>
    </div>

    <div class="actions text-center">
      <%= form.submit class: "btn btn-danger"%>
    </div>
  </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container">
  <div class="row mt-2 ft">
    <div class="col-md-8 col-md-offset-2">
      <p id="notice"><%= notice %></p>

      <h1 class="text-center">Projects</h1>

      <table class="table table-striped projects-table">
        <thead>
          <tr>
            <th>Title</th>
            <th>User</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <!-- below line was originall project.user.id which breaks in dev -->
            <% if project.user_id == @user.id %>
              <tr>
                <td>
                  <%= link_to user_project_path(@user,project) do %>
                  <%= project.title %>
                  <% end %>
                </td>
                <td><%= link_to edit_user_registration_path do %>
                  <%= project.user.first_name %> <%= project.user.last_name %></td>
                <td>
                  <%= link_to user_project_path(@user,project), method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fas fa-trash"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Project', new_user_project_path, class: "btn btn-danger new-project"%>

    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row project-form">
    <h1 class= "text-center">New Project</h1>

    <%= render 'form', project: @project %>

    <ul class="pager">
      <li class="previous">
        <%= link_to user_projects_path, class: 'col-md-offset-3' do %>
          <span aria-hidden="true">&larr;</span>
        <% end %>
      </li>
    </ul>

  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col-md-8 col-md-offset-2">

      <p id="notice"><%= notice %></p>

      <div class="title text-center">

        <ul class="pager" style="transform:translateY(150%)">
          <%= link_to :back do %>
          <li class="previous">
            <span aria-hidden="true">&larr;</span>
          </li>
          <% end %>
        </ul>


        <h1><%= @project.title %> <small>by <%= @project.user.first_name %> <%= @project.user.last_name %></small></h1>
      </div>

      <br>

      <div class="page-header">
        <h1><small>Project Introduction</small></h1>
        <p><%= @project.intro %></p>
      </div>

      <div class="page-header">
        <h1><small>Project Impact</small></h1>
        <p><%= @project.impact %></p>
      </div>

      <div class="page-header">
        <h1><small>Business Case</small></h1>
        <p><%= @project.businesscase %></p>
      </div>

    </div>
  </div>
</div>