config/routes.rb
Rails.application.routes.draw do
  resources :resources
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
    resources :projects
  end

  default_url_options :host => "http://localhost:3000"

  root 'static#home'

  resources :chapters

  get "wait" => "wait#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :country
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :users

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all.order("city ASC")
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.fetch(:chapter, {})
      params.require(:chapter).permit(:city, :country_id, user_attributes: [:first_name,:last_name,:email])
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_with(model: chapter, local: true, class: "mt-3 mb-4") do |form| %>
<% if chapter.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

  <ul>
    <% chapter.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-8 col-xs-offset-2">
    <div class="field form-group">
      <%= form.label :city %>
      <%= form.text_field :city, class:"form-control"%>
    </div>
  </div>
  <div class="col-md-4 col-md-offset-4 col-xs-8 col-xs-offset-2">
    <div class="field form-group">
      <%= form.label 'Country' %> <br>
      <%= collection_select(:chapter, :country_id, Country.all, :id, :name, prompt: 'Please choose a chapter', class:'form-control') %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4  col-xs-8 col-xs-offset-2">
    <div class="field form-group">
      <%= form.label 'Lead' %>
      <%= collection_select(:users, :user_id, User.all, :id, :full_name, prompt: 'Select a lead', class:'form-control') %>
    </div>
    <small>Add another user + </small>
  </div>
</div>

<!-- <%# @chapter.users.each_with_index do |chap_user, i| %>
  <%#= chap_user.first_name %> <%#= chap_user.last_name %>
  <%# form.fields_for :users, chap_user do |user_fields| %>
    <div class="row">
      <div class="col-md-4 col-md-offset-4  col-xs-8 col-xs-offset-2">
        <small>User <%#= i + 1 %></small>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2 col-md-offset-4  col-xs-8 col-xs-offset-2">
        <div class="field form-group">
          <%#= user_fields.label 'First Name' %>
          <%#= user_fields.text_field :first_name, value: chap_user.first_name,class:"form-control"%>
        </div>
      </div>
      <div class="col-md-2 col-md-offset-0 col-xs-8 col-xs-offset-2">
        <div class="field form-group">
          <%#= user_fields.label 'Last Name' %>
          <%#= user_fields.text_field :last_name, value: chap_user.last_name, class:"form-control"%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-xs-8 col-xs-offset-2">
        <div class="field form-group">
          <%#= user_fields.label :email %>
          <%#= user_fields.text_field :email, value: chap_user.email, class:"form-control"%>
        </div>
      </div>
    </div>
  <%# end %>
<%# end %> -->

<div class="row">
  <div class="col-xs-12 text-center">
    <div class="actions">
      <%= form.submit "Update", class: "btn btn-danger" %>
    </div>
  </div>
</div>
<% end %>

app/views/chapters/edit.html.erb
<div class="row text-center chapters mt-1">
  <div class="col-xs-4">
    <%= link_to "Back", @chapter %>
  </div>
  <div class="col-xs-4">
    <h2 class="title">Edit <%= @chapter.city %></h2>
  </div>
  <div class="col-xs-4">
    <%= link_to 'Chapters', chapters_path %>
  </div>
</div>
<div class="row text-center">
  <%= render 'form', chapter: @chapter %>
</div>

app/views/chapters/index.html.erb
<div class="container chapters">
  <p id="notice"><%= notice %></p>

  <div class="row text-center">
    <div class="col-xs-4">
    </div>
    <div class="col-xs-4">
      <h1 class="title">Chapters</h1>
    </div>
    <div class="col-xs-4">
      <%= link_to 'New Chapter', new_chapter_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1">
      <table class="table">
        <thead>
          <tr>
            <th >City</th>
            <th >Lead(s)</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @chapters.each do |chapter| %>
            <tr>
              <td>
                <%= link_to chapter do %>
                  <%= chapter.city %>
                <% end %>
              </td>
              <td>
                <% chapter.users.each_with_index do |lead, index| %>
                  <% if index != (chapter.users.length[-1] + 1 ) %>
                    <%= lead.first_name %> <%= lead.last_name %>,
                  <% else %>
                    <%= lead.first_name %> <%= lead.last_name %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
              <td><%= link_to 'X', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>


<br>

app/views/chapters/new.html.erb
<div class="row text-center chapters mt-1">
  <div class="col-xs-4">
    <%= link_to 'Back', chapters_path %>
  </div>
  <div class="col-xs-4">
    <h2 class="title">New Chapter</h2>
  </div>
  <div class="col-xs-4">
  </div>
</div>
<div class="row text-center">
  <%= render 'form', chapter: @chapter %>
</div>

app/views/chapters/show.html.erb
<div class="container chapters">
  <p id="notice"><%= notice %></p>

  <div class="row text-center">
    <div class="col-xs-2">
      <%= link_to 'Chapters', chapters_path %>
    </div>
    <div class="col-xs-8">
      <h2 class="title"><%= @chapter.city %></h2>
      <h4 class="subtitle"><%= @chapter.country.name %></h4>
    </div>
    <div class="col-xs-2">
      <%= link_to 'Edit', edit_chapter_path(@chapter) %>
    </div>
  </div>
  <div class="row text-center" style="margin:30px 0">
    <h4>Lead(s)</h4>
    <% @chapter.users.each do |chap_user| %>
    <h5><%= chap_user.first_name %> <%= chap_user.last_name %></h5>
    <% end %>
  </div>
</div>